name: Yad2 Scraper

on:
  schedule:
    - cron: "0 9,17 * * *"
  workflow_dispatch:
    branches:
      - "**"

jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages
        run: yarn install

      - name: Run scraper
        run: |
          export API_TOKEN=${{ secrets.API_TOKEN }}
          export CHAT_ID=${{ secrets.CHAT_ID }}
          export GOOGLE_SERVICE_ACCOUNT_JSON='${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}'
          export GOOGLE_SPREADSHEET_ID=${{ secrets.GOOGLE_SPREADSHEET_ID }}
          export SCRAPER_PROJECTS='${{ vars.SCRAPER_PROJECTS }}'
          yarn scrape
